// apps/ninjacore-web/src/app/clients/[id]/page.tsx
import Link from 'next/link';
import { headers } from 'next/headers';
import { api, ApiError } from '@/lib/api';
import type { ClientDetailResponse } from '@/lib/types';
import BureauCards from '@/components/BureauCards';

export const dynamic = 'force-dynamic';

export default async function ClientDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const cookie = (await headers()).get('cookie') || '';

  let data: ClientDetailResponse | null = null;
  let error: string | null = null;
  try {
    data = await api<ClientDetailResponse>(`/api/clients/${encodeURIComponent(id)}`, { cookie });
  } catch (err) {
    error = err instanceof ApiError ? `${err.status}: ${err.body.slice(0, 200)}` : String(err);
  }

  return (
    <div className="max-w-7xl mx-auto px-6 py-8">
      <Link href="/clients" className="text-xs text-white/50 hover:text-white">
        ← Back to clients
      </Link>

      {error && (
        <div className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm">
          <div className="font-semibold text-red-300">API error</div>
          <pre className="text-red-200/80 mt-1 whitespace-pre-wrap">{error}</pre>
        </div>
      )}

      {data && (
        <>
          <div className="mt-3 flex items-baseline gap-4">
            <h1 className="text-3xl font-bold tracking-tight">
              {data.client.firstName} {data.client.lastName}
            </h1>
            <span className="text-sm text-white/40 tabular-nums">id: {data.client.id}</span>
          </div>
          <div className="mt-1 text-sm text-white/60">
            {data.client.email || '—'} · {data.client.monitoringAgency || '—'} ·
            last sync {data.client.lastSyncedAt ? new Date(data.client.lastSyncedAt).toLocaleString() : '—'}
          </div>

          <section className="mt-8">
            <BureauCards client={data.client} />
          </section>

          <section className="mt-8 grid gap-6 sm:grid-cols-2">
            <div className="rounded-xl border border-white/10 bg-white/5 p-4">
              <div className="text-xs uppercase tracking-wider text-white/50">Status</div>
              <div className="mt-1 text-lg">{data.client.status}</div>
              <div className="text-xs text-white/50 mt-3">Phase</div>
              <div className="text-lg">{data.client.phase}</div>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/5 p-4">
              <div className="text-xs uppercase tracking-wider text-white/50">Report</div>
              <div className="mt-1 text-lg tabular-nums">{data.client.reportDate || '—'}</div>
              <div className="text-xs text-white/50 mt-3">Open accounts</div>
              <div className="text-lg tabular-nums">{data.client.openAccounts?.length ?? 0}</div>
            </div>
          </section>
        </>
      )}
    </div>
  );
}

// apps/ninjacore-web-svelte/src/routes/clients/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { useClient } from '$lib/stores/clients';
  import { Loader2, ChevronLeft, BarChart3, Users } from 'lucide-svelte';

  const clientQuery = useClient($page.params.id);
</script>

<svelte:head>
  <title>Client · NinjaCore</title>
  <meta name="description" content="Client details and credit information" />
</svelte:head>

<div class="max-w-7xl mx-auto px-6 py-8">
  <a href="/clients" class="inline-flex items-center gap-2 text-xs text-white/50 hover:text-white/70 mb-6">
    <ChevronLeft class="w-4 h-4" />
    Back to clients
  </a>

  {#if $clientQuery.isPending}
    <div class="flex items-center gap-3 text-white/50">
      <Loader2 class="w-4 h-4 animate-spin" />
      <span>Loading client details…</span>
    </div>
  {:else if $clientQuery.error}
    <div class="rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm">
      <div class="font-semibold text-red-300">Error</div>
      <pre class="text-red-200/80 mt-1">{String($clientQuery.error)}</pre>
    </div>
  {:else if $clientQuery.data}
    {@const client = $clientQuery.data.client}
    <div class="space-y-8">
      {/* Header */}
      <div>
        <h1 class="text-4xl font-bold tracking-tight mb-2">
          {client.firstName} {client.lastName}
        </h1>
        <p class="text-white/60">
          {client.email} · {client.monitoringAgency} · ID: {client.id}
        </p>
      </div>

      {/* Stats Grid */}
      <div class="grid gap-4 sm:grid-cols-4">
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Status</div>
          <div class="text-2xl font-semibold">{client.status}</div>
        </div>
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Phase</div>
          <div class="text-2xl font-semibold">{client.phase}</div>
        </div>
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Days Left</div>
          <div class={`text-2xl font-semibold ${client.daysLeft && client.daysLeft < 0 ? 'text-red-400' : 'text-white'}`}>
            {typeof client.daysLeft === 'number' ? client.daysLeft : '—'}
          </div>
        </div>
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Last Report</div>
          <div class="text-lg font-semibold">{client.reportDate || '—'}</div>
        </div>
      </div>

      {/* Bureau Scores */}
      {#if client.creditScores}
        <div class="rounded-lg border border-white/10 bg-white/5 p-6">
          <div class="flex items-center gap-2 mb-4">
            <BarChart3 class="w-5 h-5 text-cyan-400" />
            <h2 class="text-xl font-semibold">Credit Scores</h2>
          </div>
          <div class="grid gap-4 sm:grid-cols-3">
            {#each Object.entries(client.creditScores) as [bureau, score]}
              <div class="rounded-lg bg-white/5 p-4 border border-white/10">
                <div class="text-sm text-white/60 uppercase tracking-wider mb-2">{bureau}</div>
                <div class="text-3xl font-bold text-cyan-400">{score}</div>
              </div>
            {/each}
          </div>
        </div>
      {/if}

      {/* Contact Info */}
      <div class="grid gap-4 sm:grid-cols-2">
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Email</div>
          <div class="font-medium">{client.email || '—'}</div>
        </div>
        <div class="rounded-lg border border-white/10 bg-white/5 p-4">
          <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Phone</div>
          <div class="font-medium">{client.phone || '—'}</div>
        </div>
        {#if client.dob}
          <div class="rounded-lg border border-white/10 bg-white/5 p-4">
            <div class="text-xs uppercase tracking-wider text-white/50 mb-2">DOB</div>
            <div class="font-medium">{client.dob}</div>
          </div>
        {/if}
        {#if client.address}
          <div class="rounded-lg border border-white/10 bg-white/5 p-4">
            <div class="text-xs uppercase tracking-wider text-white/50 mb-2">Address</div>
            <div class="font-medium">{client.address}</div>
          </div>
        {/if}
      </div>

      {/* Open Accounts */}
      {#if client.openAccounts && client.openAccounts.length > 0}
        <div class="rounded-lg border border-white/10 bg-white/5 p-6">
          <div class="flex items-center gap-2 mb-4">
            <Users class="w-5 h-5 text-emerald-400" />
            <h2 class="text-xl font-semibold">Open Accounts</h2>
          </div>
          <div class="text-white/70">
            {client.openAccounts.length} account(s) found
          </div>
        </div>
      {/if}
    </div>
  {/if}
</div>
